config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :milis, only: [:index]
  resources :deles, only: [:index]
  resources :domains do
    get :test, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  def name
    self.l_name.to_s + ' ' + self.f_name.to_s
  end

  def kana
    self.l_kana.to_s + self.f_kana.to_s
  end

  def to_boin
    boin = self.roma
    boin = boin.gsub(/na/,'a')
    boin = boin.gsub(/ni/,'i')
    boin = boin.gsub(/nu/,'u')
    boin = boin.gsub(/ne/,'e')
    boin = boin.gsub(/no/,'o')
    boin = boin.gsub(/[^aiueon]/,'')
    boin
  end
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def to_boin(text)
    text = text.gsub(/na/,'a')
    text = text.gsub(/ni/,'i')
    text = text.gsub(/nu/,'u')
    text = text.gsub(/ne/,'e')
    text = text.gsub(/no/,'o')
    text = text.gsub(/[^aiueon]/,'')
    text
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  require "romaji/core_ext/string"

  def index
    # 表示いい感じに
    # 他のサイトを見てみる
    # 辞書を登録しまくる
    # 同じ韻の単語を出す
    # https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1213120447
    # 単語の品詞ごとに使い方をみる10種類ある
    # 韻の説明ページを作成
    # 765メンバーの重複

    # Gemの利用
binding.pry
    @t7s = T7s.find_by_id(1).name
    @t7s = T7s.find_by_name('ニコ')


    search = { }
    if params.present? && params[:q].present?
      #next unless params[:q][:search_word_start].present?
      @search_word = params[:q][:search_word_start]
      # バリデーション
      if @search_word.match(/[^ぁ-ん]/)
        @alert = 'ひらがなで入力して下さい。'
      end
      # 変換
      @search_word_start = to_boin(@search_word.romaji)
      search[:search_word_start] = @search_word_start
      search[:search_word_start].reverse!
      # 文字数制限
      search[:search_word_start] = @search_word_start[0, params[:word_limit].to_i] if params[:word_limit].present?
    end

    @q = Character.search(search)
    @characters = @q.result(distinct: true) #.page(params[:page])
  end
end

app/controllers/deles_controller.rb
class DelesController < ApplicationController
  require "romaji/core_ext/string"

  def index
    list = ['a','i','u','e','o','n']
    @characters = []
    list.each_with_index do |var, i|
      @characters[i] = Character.where(contents: 2).search({ search_word_start: var }).result(distinct: true)
    end
#binding.pry
  end
end

app/controllers/milis_controller.rb
class MilisController < ApplicationController
  require "romaji/core_ext/string"

  def index
    list = ['a','i','u','e','o','n']
    @characters = []
    list.each_with_index do |var, i|
      @characters[i] = Character.where(contents: 1).search({ search_word_start: var }).result(distinct: true)
    end
#binding.pry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def is_domain(roma)
    #domains = ['website','wed','wedding','weibo','wien','wiki','win','wine','work','works','world','wtf','xin','xyz','yoga','yokohama','yun','zip','zone','zuerich']
    domains = ['com','net','press','space','work','pw','site','xyz','club','info','online','tokyo','top','website','biz','life','me','mobi','shop','fun','tech','org','pro','cloud','asia','bio','green','host','organic','world','blue','pink','red','co','style','art','design','games','love','news','日本語jp','promo','men','ski','jp','poker','ai']
    #domains = []
    domains.each do |domain|
      if roma.end_with?(domain)
        url = 'http://' + roma.sub(/#{domain}$/,'') + '.' + domain
        return link_to url, url, target: 'blank'
      end
    end
    return ''
  end
end

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %>
    <%= f.number_field :game_id %>
  </div>

  <div class="field">
    <%= f.label :l_name %>
    <%= f.text_field :l_name %>
  </div>

  <div class="field">
    <%= f.label :f_name %>
    <%= f.text_field :f_name %>
  </div>

  <div class="field">
    <%= f.label :l_kana %>
    <%= f.text_field :l_kana %>
  </div>

  <div class="field">
    <%= f.label :f_kana %>
    <%= f.text_field :f_kana %>
  </div>

  <div class="field">
    <%= f.label :roma %>
    <%= f.text_field :roma %>
  </div>

  <div class="field">
    <%= f.label :search_word %>
    <%= f.text_field :search_word %>
  </div>

  <div class="field">
    <%= f.label :cv_id %>
    <%= f.text_field :cv_id %>
  </div>

  <div class="field">
    <%= f.label :idol_type %>
    <%= f.text_field :idol_type %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>

  <div class="field">
    <%= f.label :blood_type %>
    <%= f.text_field :blood_type %>
  </div>

  <div class="field">
    <%= f.label :bust %>
    <%= f.text_field :bust %>
  </div>

  <div class="field">
    <%= f.label :waist %>
    <%= f.text_field :waist %>
  </div>

  <div class="field">
    <%= f.label :hip %>
    <%= f.text_field :hip %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :memo %>
    <%= f.text_field :memo %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<div class="container">
  <%= @alert %>
  <%= search_form_for @q, class: 'form-inline' do |f| %>
    <div class="form-group">
      <%#= f.label :l_name_eq %><br />
      <%#= f.text_field :l_name_eq, class: 'form-control' %>
      <%= f.label '韻を踏みたい単語を「ひらがな」で入力して下さい。' %><br />
      <%= f.text_field :search_word_start, { value: @search_word, class: 'form-control' } %>
      <%= select_tag :word_limit, options_for_select({ "1文字": 1, "2文字": 2 }, params[:word_limit]),  include_blank: '全一致',  class: "form-control" %>
      <%= f.submit 'search', class: 'btn btn-success' %>
    </div>
  <% end %>
  <% if @search_word_start %>
    <p>【<%= @search_word %>】の韻は「<%= @search_word_start %>」です。</p>
  <% end %>
</div>
<br>

<div class="container">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <!--<th>Game</th>-->
      <th>Name</th>
      <th>Kana</th>
      <th>Roma</th>
      <th>Rhyme</th>
      <!--
      <th>Search word</th>
      <th>Idol type</th>
      <th>Description</th>
      <th>Memo</th>
      -->
      <th colspan="2">action</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.id %></td>
        <!--
        <td><%= character.game_id %></td>
        -->
        <td><%= character.name %></td>
        <td><%= character.kana %></td>
        <td><%= character.roma %></td>
        <td><%= character.search_word.reverse %></td>
        <!--
        <td><%= character.search_word %></td>
        <td><%= character.idol_type %></td>
        <td><%= character.description %></td>
        <td><%= character.memo %></td>
        -->
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>
</div>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @character.game_id %>
</p>

<p>
  <strong>L_Name:</strong>
  <%= @character.l_name %>
</p>

<p>
  <strong>F_Name:</strong>
  <%= @character.f_name %>
</p>

<p>
  <strong>L_Kana:</strong>
  <%= @character.l_kana %>
</p>

<p>
  <strong>F_Kana:</strong>
  <%= @character.f_kana %>
</p>

<p>
  <strong>Roma:</strong>
  <%= @character.roma %>
</p>

<p>
  <strong>Search word:</strong>
  <%= @character.search_word %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @character.cv_id %>
</p>

<p>
  <strong>Idol type:</strong>
  <%= @character.idol_type %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Height:</strong>
  <%= @character.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @character.weight %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @character.birthday %>
</p>

<p>
  <strong>Blood type:</strong>
  <%= @character.blood_type %>
</p>

<p>
  <strong>Bust:</strong>
  <%= @character.bust %>
</p>

<p>
  <strong>Waist:</strong>
  <%= @character.waist %>
</p>

<p>
  <strong>Hip:</strong>
  <%= @character.hip %>
</p>

<p>
  <strong>Color:</strong>
  <%= @character.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @character.memo %>
</p>

<p>
  <strong>Position:</strong>
  <%= @character.position %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>